# config/routes.yaml

controllers:
    resource: routing.controllers
    type: attribute

# La route pour le login
api_login_check:
    path: /api/login_check
    methods: ['POST']  # Ajout conseill√© : on n'autorise que le POST
