security:
    # 1. Configuration du hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2. Fournisseurs d'utilisateurs
    providers:
        # Ici, on dit à Symfony d'aller chercher les utilisateurs dans l'entité User
        # via leur adresse email.
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 3. Configuration des pare-feux (Firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall pour la connexion (login)
        # C'est ici que le JWT est créé si l'email/mot de passe sont bons
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email      # On précise que le champ JSON est "email" et non "username"
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall pour protéger l'API
        # Toutes les routes commençant par /api (sauf login) passeront par ici
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~  # Active la vérification du token JWT

        # Firewall par défaut (laisse passer le reste ou redirige, optionnel ici)
        main:
            lazy: true
            provider: app_user_provider

    # 4. Contrôle d'accès (ACL)
    access_control:
        # On autorise tout le monde à essayer de se connecter
        - { path: ^/api/login, roles: PUBLIC_ACCESS }

        # On oblige d'être connecté pour accéder au reste de l'API
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

# Optimisation pour les tests (ne pas toucher)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
